
services:
  minecraft-1.21.1:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      TYPE: "VANILLA"
      VERSION: 1.21.1
    ports:
      - ${SQUADGOALS_MINECRAFT_1_21_1_PORT}:25565
      - ${SQUADGOALS_MINECRAFT_1_21_1_PORT_RCON}:25575
    volumes:
      - "${SQUADGOALS_SERVERS_MINECRAFT_DATAS}/${SQUADGOALS_MINECRAFT_1_21_1_DATA}:/data"
      - "${SQUADGOALS_SERVERS_MINECRAFT_WORLDS}/${SQUADGOALS_MINECRAFT_1_21_1_WORLD}:/data/world"
