
services:
  minecraft-ftb-evolution-1.7.0:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      TYPE: "FTBA"
      FTB_MODPACK_ID: 125
      FTB_MODPACK_VERSION_ID: 100018
    ports:
      - ${SQUADGOALS_MINECRAFT_FTB_EVOLUTION_1_7_0_PORT}:25565
    volumes:
      - "${SQUADGOALS_SERVERS_MINECRAFT_DATAS}/${SQUADGOALS_MINECRAFT_FTB_EVOLUTION_1_7_0_DATA}:/data"
      - "${SQUADGOALS_SERVERS_MINECRAFT_WORLDS}/${SQUADGOALS_MINECRAFT_FTB_EVOLUTION_1_7_0_WORLD}:/data/world"
