
services:
  minecraft-ftb-revelation-3.7.0:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      TYPE: "FTBA"
      FTB_MODPACK_ID: 35
      FTB_MODPACK_VERSION_ID: 12180
    ports:
      - ${SQUADGOALS_MINECRAFT_FTB_REVELATION_3_7_0_PORT}:25565
      - ${SQUADGOALS_MINECRAFT_FTB_REVELATION_3_7_0_PORT_RCON}:25575
    volumes:
      - "${SQUADGOALS_SERVERS_MINECRAFT_DATAS}/${SQUADGOALS_MINECRAFT_FTB_REVELATION_3_7_0_DATA}:/data"
      - "${SQUADGOALS_SERVERS_MINECRAFT_WORLDS}/${SQUADGOALS_MINECRAFT_FTB_REVELATION_3_7_0_WORLD}:/data/world"
